### ISSUE TITLE
Structure generator should include default values

### ISSUE THREAD

**Issue by depwl9992** [dmkilday/GameMaster-GPT#12]
![image](https://github.com/dmkilday/GameMaster-GPT/assets/1482452/d21faf4e-8e07-44e2-b9bb-102eddf2f881)
As you can see, the keywords and character sheet are optional, but numeric values must be explicitly provided by the user. Would be nice if a blank (or invalid) string just assumed a default for Number of Stages, Minimum Substages, and Maximum Substages.

**Comment by depwl9992** [comment]
Refer to #7 for scope

**Comment by dmkilday** [comment]
Implemented defaulting to 3 if the user leaves these options blank. Also, implemented error handling to make sure they enter a number.
