### ISSUE TITLE
Develop functionality to generate the JSON adventure module based on an adventure premise

### ISSUE THREAD

**Issue by depwl9992** [dmkilday/GameMaster-GPT#7]
> Almost done with this one! Hopefully will submit a pull request for it today. The output of this function will essentially be a JSON formatted D&D adventure which will be the basis for d7d.py to facilitate a game.

**Comment by depwl9992** [comment]
Refer to #12 for needed bug fixes in this area.

**Comment by dmkilday** [comment]
Implemented gen_adventure.py which creates the expanded module JSON.
